CREATE TABLE `boltPatterns` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`stud` DECIMAL(4,2) NOT NULL,
	`pcd` DECIMAL(5,2) NOT NULL COMMENT 'Pitch Circle Diameter',
	`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;