CREATE TABLE `collections` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`parentId` INT(11) NOT NULL DEFAULT '0',
	`brandId` INT(11) NOT NULL,
	`name` VARCHAR(100) NOT NULL,
	`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

ALTER TABLE `wheels`
	ADD COLUMN `collectionId` INT(11) NOT NULL AFTER `brandId`;